spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  profiles:
      include:
        test
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE